services:
  soybean-flask-service:
    build:
      context: ./soybean-seeds-quality-classification/flask-service
    ports:
      - "5001:5001"
    networks:
      - backend

  corn-flask-service:
    build:
      context: ./corn-seeds-quality-classification/flask-service
    ports:
      - "5003:5003"
    networks:
      - backend
  
  rice-flask-service:
    build:
      context: ./rice-disease-prediction/flask-service
    ports:
      - "5009:5009"
    networks:
      - backend

  soybean-express-service:
    build:
      context: ./soybean-seeds-quality-classification/express-service
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - soybean-flask-service

  corn-express-service:
    build:
      context: ./corn-seeds-quality-classification/express-service
    ports:
      - "5002:5002"
    networks:
      - backend
    depends_on:
      - corn-flask-service
  
  rice-express-service:
    build:
      context: ./rice-disease-prediction/express-service
    ports:
      - "5008:5008"
    networks:
      - backend
    depends_on:
      - rice-flask-service

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - soybean-express-service
      - corn-express-service
      - rice-express-service
    networks:
      - backend

networks:
  backend:
    driver: bridge
